backend:
  name: github
  repo: canfie1d/modify
  branch: prod
display_url: https://modifyhair.com
media_folder: "public/assets/images/uploads" # Media files will be stored here
public_folder: "static/media/images" # The src attribute for uploaded media
publish_mode: editorial_workflow

collections:
  - name: "stylists" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Stylists" # Used in the UI
    label_singular: "Stylist" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "_stylists"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"} # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "../src/Content/Home/home-content.json"
        fields:
          - {label: Paragraph 1, name: paragraph1, widget: text}
          - {label: Paragraph 2, name: paragraph2, widget: text}
          - label: Photos
            name: photos
            widget: list
            fields:
              # - {label: Name, name: name, widget: string}
              # - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
              - {label: Photo, name: photo, widget: image}
      # - label: "Stylists Page"
      #   name: "stylists"
      #   file: "src/Content/Home/stylist-content.json"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: text}
      #     - label: Team
      #       name: team
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Position, name: position, widget: string}
      #         - {label: Photo, name: photo, widget: image}

  # - name: "home-images"
  #   label: "Home Images"
  #   folder: "src/Content/Home"
  #   create: true
  #     fields:
  #       label: "Home Image"
  #       name: "homeImage"
  #       fields:
  #       - label: "Image"
  #         name: "title"
  #         widget: "object"
  #         fields:
  #           [{label: Image, name: url, widget: image}, {label: Image Description, name: alt, widget: string}]
  # - name: "stylists"
  #   label: "Stylists"
  #   folder: "src/Content/Stylists"
  #   format: json
  #   create: true
  #   fields:
  #       - label: "Stylist"
  #         name: "title"
  #         widget: "object"
  #         fields:
  #           - {label: "Name", name: "title", widget: "string" }
  #           - {label: "Position", name: "position", widget: "string"}
  #           - {label: "Image", name: "image", widget: "image"}
  #           - {label: "Bio", name: "bio", widget: "string"}
  #           - {label: "Bio Continued", name: "bio2", widget: "string"}
  #           - {label: "Contact", name: "contact", widget: "string" }
  #           - {label: "Website", name: "website", widget: "string", required: false }
  #           - {label: "Phone Number", name: "phone", widget: "string", required: false }
  #           - {label: "Email", name: "email", widget: "string", required: false}

  # - name: "services"
  #   label: "Services"
  #   folder: "src/Content/Services"
  #   format: json
  #   create: true
  #   fields:
  #     - label: "Service"
  #       name: "title"
  #       widget: "object"
  #       fields:
  #         - {label: "Service Name", name: "title", widget: "string" }
  #         - {label: "Service Cost", name: "serviceCost", widget: "string"}
