backend:
  name: github
  repo: canfie1d/modify
  branch: prod

media_folder: "assets/images/uploads"

collections: 
  - name: "home-content"
    label: "Home Content"
    folder: "content/home-content" 
    slug: "{{name}}"
    create: true
    fields:
        - {label: "Intro Paragraph", name: "intro", widget: "string" }

  - name: "home-images"
    label: "Home Images"
    folder: "content/home-images"
    slug: "{{name}}"
    create: true
    fields:
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Alt Text", name: "alttext", widget: "string"}

  - name: "stylists"
    label: "Stylists"
    folder: "content/stylists"
    slug: "{{name}}"
    create: true
    fields:
        - {label: "Name", name: "name", widget: "string" }
        - {label: "Position", name: "position", widget: "string"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Bio", name: "bio", widget: "string"}
        - {label: "Bio Continued", name: "bio2", widget: "string"}
        - {label: "Contact", name: "contact", widget: "string" }
        - {label: "Website", name: "website", widget: "string" }
        - {label: "Phone Number", name: "phone", widget: "string" }
        - {label: "Email", name: "email", widget: "string"}
        - {label: "Instagram Name", name: "instagram", widget: "string" }

  - name: "services" 
    label: "Services"
    folder: "src/Content/Services"
    slug: "{{name}}"
    create: true
    fields:
        - {label: "Service", name: "servicename", widget: "string" }
        - {label: "Cost", name: "servicecost", widget: "string"}
